# Generated by Django 3.0.5 on 2020-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="shared_with",),
        migrations.AlterField(
            model_name="project",
            name="type_of_project",
            field=models.CharField(
                choices=[
                    ("TK", "Task project"),
                    ("FN", "Finance project"),
                    ("DR", "Diary project"),
                ],
                default="TK",
                max_length=2,
            ),
        ),
    ]
