# Generated by Django 2.2.6 on 2019-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_project'),
        ('projects', '0002_auto_20191031_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
