# Generated by Django 2.2.6 on 2019-11-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
    ]
