# Generated by Django 2.2.6 on 2019-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_of_project',
            field=models.IntegerField(choices=[(1, 'Task project'), (2, 'Budget project'), (3, 'Diary project')], default=1),
        ),
    ]
