version: "3.7"
services:
  app:
    build: .
    image: timelyapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code/app
      - ./manage.py:/code/manage.py
      - ./db.sqlite3:/code/db.sqlite3
      - ./tasks.py:/code/tasks.py
    ports:
      - 8000:8000
