# Generated by Django 2.2.6 on 2019-10-25 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="shared_with",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
