# Generated by Django 2.2.6 on 2019-10-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tasks", "0002_auto_20191031_1634")]

    operations = [migrations.RemoveField(model_name="task", name="project")]
