# Generated by Django 2.2.6 on 2019-10-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done',
            new_name='completed',
        ),
    ]
